// src/api/mockData.js
// Realistic sample data matching the full Module 4 SQLite schema.
// Used when VITE_USE_MOCK=true in .env.local

export const MOCK_CALLS = [
  {
    call_id:            'CALL-001',
    timestamp:          '2025-01-15T10:32:00Z',
    transcript:         'Customer asked about home loan options. Mentioned budget of 80 lakhs and wanted to visit the branch. Very engaged with EMI details.',
    language:           'en',
    pitch_mean:         210.45,
    speech_rate:        165,
    duration_sec:       187,
    energy_delta:       12.4,
    tone:               'Enthusiastic',
    has_budget:         1,
    has_loan:           1,
    has_visit:          1,
    keyword_norm:       0.8,
    question_norm:      0.72,
    engagement_score:   0.91,
    sentiment:          'positive',
    duration_norm:      0.62,
    context_scores:     { budget: 0.89, visit: 0.76, loan: 0.92, keyword: 0.87, question: 0.72, engagement: 0.91 },
    llm_holistic_score: 0.88,
    signal_score:       0.86,
    intent_score:       0.92,
    intent_class:       'Very Strong',
    confidence:         0.94,
    reasoning: [
      'Customer explicitly mentioned budget of 80 lakhs',
      'Requested branch visit appointment',
      'Asked 7 specific EMI-related questions',
      'Past call prev_call_CC203 — similar budget signal converted',
    ],
    evidence_refs:    ['CALL_CC203', 'RULE_07'],
    learning_insight: ['Visit signal is primary driver for this call type'],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.28, visit: 0.33, loan: 0.10, keyword: 0.11, question: 0.09, engagement: 0.07, tone: 0.03, sentiment: 0.02 },
    transcript_segments: [
      { speaker: 'SPEAKER_00', text: 'Hello, am I speaking to Mr. Haswanth?' },
      { speaker: 'SPEAKER_01', text: 'Yes, I am looking for a home loan. My budget is around 80 lakhs.' },
      { speaker: 'SPEAKER_00', text: 'Great, we have several options. Would you like to visit the branch?' },
      { speaker: 'SPEAKER_01', text: 'Yes, I want to visit and understand the EMI schedule. What is the EMI for 80 lakhs over 20 years?' },
      { speaker: 'SPEAKER_00', text: 'For 80 lakhs at 8.5%, your EMI would be approximately 69,000 per month.' },
      { speaker: 'SPEAKER_01', text: 'That is fine. Can you schedule a visit for this Saturday? I also want to understand the loan processing fee and budget for it.' },
    ],
    speakers: {
      SPEAKER_00: { energy_delta: 2.1,  tone: 'Confident' },
      SPEAKER_01: { energy_delta: 16.3, tone: 'Enthusiastic' },
    },
    speakers_nlp: {
      SPEAKER_00: { has_budget: 0, has_loan: 0, has_visit: 1, question_count: 0, sentiment: 'positive',  keyword_norm: 0.2, question_norm: 0.0 },
      SPEAKER_01: { has_budget: 1, has_loan: 1, has_visit: 1, question_count: 4, sentiment: 'positive',  keyword_norm: 0.8, question_norm: 0.72 },
    },
    outcome: null,
  },
  {
    call_id:            'CALL-002',
    timestamp:          '2025-01-15T11:05:00Z',
    transcript:         'Customer inquired about personal loan. Seemed interested but hesitant about interest rates.',
    language:           'en',
    pitch_mean:         185.2,
    speech_rate:        142,
    duration_sec:       605,
    energy_delta:       -8.3,
    tone:               'Hesitant',
    has_budget:         0,
    has_loan:           1,
    has_visit:          0,
    keyword_norm:       0.4,
    question_norm:      0.4,
    engagement_score:   0.58,
    sentiment:          'neutral',
    duration_norm:      1.0,
    context_scores:     { budget: 0.12, visit: 0.08, loan: 0.71, keyword: 0.61, question: 0.54, engagement: 0.58 },
    llm_holistic_score: 0.55,
    signal_score:       0.48,
    intent_score:       0.61,
    intent_class:       'Strong',
    confidence:         0.73,
    reasoning: [
      'Customer asked multiple loan structure questions — high cognitive investment',
      'Hesitant tone but questions are deep-funnel — quiet buyer pattern',
      'No site visit or budget confirmation',
    ],
    evidence_refs:    ['CALL_CC089', 'RULE_03'],
    learning_insight: ['Hesitant tone with technical questions — monitor closely'],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.22, visit: 0.29, loan: 0.18, keyword: 0.12, question: 0.11, engagement: 0.05, tone: 0.03, sentiment: 0.02 },
    transcript_segments: [
      { speaker: 'SPEAKER_00', text: 'Good morning, how can I help you today?' },
      { speaker: 'SPEAKER_01', text: 'I want to understand personal loan options. What is the interest rate?' },
      { speaker: 'SPEAKER_00', text: 'Our personal loans start at 10.5% per annum.' },
      { speaker: 'SPEAKER_01', text: 'That seems high. Do you have any finance schemes with lower rates for existing customers?' },
    ],
    speakers: {
      SPEAKER_00: { energy_delta: 1.2,  tone: 'Confident' },
      SPEAKER_01: { energy_delta: -8.3, tone: 'Hesitant' },
    },
    speakers_nlp: {
      SPEAKER_00: { has_budget: 0, has_loan: 1, has_visit: 0, question_count: 0, sentiment: 'positive', keyword_norm: 0.2, question_norm: 0.0 },
      SPEAKER_01: { has_budget: 0, has_loan: 1, has_visit: 0, question_count: 2, sentiment: 'neutral',  keyword_norm: 0.4, question_norm: 0.4 },
    },
    outcome: 'follow_up',
  },
  {
    call_id:            'CALL-003',
    timestamp:          '2025-01-15T11:22:00Z',
    transcript:         'Customer called to ask about hours. Not interested in products. Very short call.',
    language:           'en',
    pitch_mean:         162.0,
    speech_rate:        110,
    duration_sec:       682,
    energy_delta:       -22.1,
    tone:               'Hesitant',
    has_budget:         0,
    has_loan:           0,
    has_visit:          0,
    keyword_norm:       0.0,
    question_norm:      0.2,
    engagement_score:   0.08,
    sentiment:          'negative',
    duration_norm:      1.0,
    context_scores:     { budget: 0.0, visit: 0.0, loan: 0.0, keyword: 0.0, question: 0.1, engagement: 0.05 },
    llm_holistic_score: 0.05,
    signal_score:       0.03,
    intent_score:       0.11,
    intent_class:       'No Chance',
    confidence:         0.95,
    reasoning: [
      'No purchase-related keywords detected',
      'Customer explicitly stated not interested',
      'All questions were about branch hours — not product-related',
    ],
    evidence_refs:    [],
    learning_insight: [],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.25, visit: 0.30, loan: 0.10, keyword: 0.10, question: 0.10, engagement: 0.10, tone: 0.03, sentiment: 0.02 },
    transcript_segments: [
      { speaker: 'SPEAKER_00', text: 'Thank you for calling. How can I help?' },
      { speaker: 'SPEAKER_01', text: 'I just wanted to know your branch timings. I am not interested in any products.' },
    ],
    speakers: {
      SPEAKER_00: { energy_delta: 0.5,   tone: 'Confident' },
      SPEAKER_01: { energy_delta: -22.1, tone: 'Hesitant' },
    },
    speakers_nlp: {
      SPEAKER_00: { has_budget: 0, has_loan: 0, has_visit: 0, question_count: 0, sentiment: 'positive', keyword_norm: 0.0, question_norm: 0.0 },
      SPEAKER_01: { has_budget: 0, has_loan: 0, has_visit: 0, question_count: 1, sentiment: 'negative', keyword_norm: 0.0, question_norm: 0.2 },
    },
    outcome: 'not_interested',
  },
  {
    call_id:            'CALL-004',
    timestamp:          '2025-01-15T12:41:00Z',
    transcript:         'Customer asked about 2BHK property options near OMR. Budget 50 lakhs. Site visit tentative.',
    language:           'ta',
    pitch_mean:         225.0,
    speech_rate:        178,
    duration_sec:       761,
    energy_delta:       9.8,
    tone:               'Confident',
    has_budget:         1,
    has_loan:           1,
    has_visit:          0,
    keyword_norm:       0.6,
    question_norm:      0.6,
    engagement_score:   0.76,
    sentiment:          'positive',
    duration_norm:      1.0,
    context_scores:     { budget: 0.78, visit: 0.42, loan: 0.60, keyword: 0.71, question: 0.65, engagement: 0.76 },
    llm_holistic_score: 0.78,
    signal_score:       0.69,
    intent_score:       0.74,
    intent_class:       'Strong',
    confidence:         0.81,
    reasoning: [
      'Budget of 50 lakhs confirmed by customer',
      'Loan inquiry phrased as personal need — context score 0.60',
      'Visit not explicitly committed — context score 0.42',
    ],
    evidence_refs:    ['RULE_05'],
    learning_insight: ['Budget + loan combination strong predictor for Tamil-speaking callers'],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.26, visit: 0.31, loan: 0.14, keyword: 0.10, question: 0.10, engagement: 0.06, tone: 0.03, sentiment: 0.02 },
    transcript_segments: null,
    speakers:     null,
    speakers_nlp: null,
    outcome: null,
  },
  {
    call_id:            'CALL-005',
    timestamp:          '2025-01-15T14:10:00Z',
    transcript:         'Long call, many questions about wall colour and parking. No purchase intent detected.',
    language:           'hi',
    pitch_mean:         198.0,
    speech_rate:        155,
    duration_sec:       860,
    energy_delta:       3.1,
    tone:               'Confident',
    has_budget:         0,
    has_loan:           0,
    has_visit:          0,
    keyword_norm:       0.0,
    question_norm:      0.8,
    engagement_score:   0.62,
    sentiment:          'neutral',
    duration_norm:      1.0,
    context_scores:     { budget: 0.0, visit: 0.05, loan: 0.0, keyword: 0.05, question: 0.15, engagement: 0.20 },
    llm_holistic_score: 0.18,
    signal_score:       0.12,
    intent_score:       0.29,
    intent_class:       'Mild',
    confidence:         0.71,
    reasoning: [
      'High question count but all questions irrelevant to purchase',
      'Time-waster pattern — engagement without intent',
      'No budget, loan, or visit signals from customer',
    ],
    evidence_refs:    ['RULE_09'],
    learning_insight: ['Engagement score alone does not indicate purchase intent'],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.25, visit: 0.30, loan: 0.10, keyword: 0.10, question: 0.10, engagement: 0.10, tone: 0.03, sentiment: 0.02 },
    transcript_segments: null,
    speakers:     null,
    speakers_nlp: null,
    outcome: null,
  },
  {
    call_id:            'CALL-006',
    timestamp:          '2025-01-15T14:55:00Z',
    transcript:         'Customer loved the property but said budget is too tight right now.',
    language:           'en',
    pitch_mean:         202.0,
    speech_rate:        148,
    duration_sec:       895,
    energy_delta:       6.2,
    tone:               'Confident',
    has_budget:         1,
    has_loan:           0,
    has_visit:          0,
    keyword_norm:       0.2,
    question_norm:      0.0,
    engagement_score:   0.29,
    sentiment:          'positive',
    duration_norm:      1.0,
    context_scores:     { budget: 0.0, visit: 0.0, loan: 0.0, keyword: 0.05, question: 0.0, engagement: 0.10 },
    llm_holistic_score: 0.12,
    signal_score:       0.05,
    intent_score:       0.21,
    intent_class:       'Very Mild',
    confidence:         0.88,
    reasoning: [
      'Budget keyword detected but context negated — "budget is too tight"',
      'Positive sentiment from enthusiasm about property, not purchase intent',
      'Polite refusal pattern — LLM assigned ctx_budget = 0.0',
    ],
    evidence_refs:    ['RULE_02'],
    learning_insight: ['Positive sentiment + negated budget = polite refusal trap'],
    customer_speaker_id: 'SPEAKER_01',
    rl_weights_used: { budget: 0.25, visit: 0.30, loan: 0.10, keyword: 0.10, question: 0.10, engagement: 0.10, tone: 0.03, sentiment: 0.02 },
    transcript_segments: null,
    speakers:     null,
    speakers_nlp: null,
    outcome: null,
  },
]

export const MOCK_LEARNING_SUMMARY = {
  current_weights: {
    budget:     0.312,
    visit:      0.007,
    loan:       0.287,
    keyword:    0.142,
    question:   0.098,
    engagement: 0.198,
    tone:       0.03,
    sentiment:  0.02,
  },
  signal_conversion_rates: {
    visit:      0.76,
    budget:     0.71,
    engagement: 0.62,
    loan:       0.58,
    keyword:    0.44,
    question:   0.39,
  },
  total_calls_learned: 248,
  buffer_size:         248,
  policy_mode:         'rl_contextual_bandit',
}

export const MOCK_PERFORMANCE = [
  { intent_class: 'Very Strong', conversion_rate: 0.85, call_count: 34 },
  { intent_class: 'Strong',      conversion_rate: 0.60, call_count: 89 },
  { intent_class: 'Mild',        conversion_rate: 0.25, call_count: 72 },
  { intent_class: 'Very Mild',   conversion_rate: 0.08, call_count: 41 },
  { intent_class: 'No Chance',   conversion_rate: 0.02, call_count: 12 },
]
